# Site settings
title:              So You Like to Build Robots
email:              alanhong2016@u.northwestern.edu
description:        "Portfolio of Alan Hong, student of the Master of Science in Robotics program at Northwestern University"
url:                "http://localhost:4000"
baseurl:            /alanhong_automaton

# File structure settings
image_path:         /public/images

# Build settings
markdown:           kramdown
permalink:          pretty

# Collection definitions and settings
collections:
  projects:
    output: true
    permalink: /projects/:path/
